version: '3'
services:
  train:
    image: vivekchiliveri/trainrepopaytm:latest
    ports:
      - "80:80"
    deploy:
      replicas: 3



      movie:
        image: vivekchiliveri/moviesrepopaytm:latest
        ports:
          - "81:80"
        deploy:
          replicas: 3



          Dth:
            image: vivekchiliveri/dthrepopaytm:latest
            ports:
              - "82:80"
            deploy:
              replicas: 3


recharge:
image: vivekchiliveri/recharerepopaytm:latest
ports:
- "83:80"
deploy:
replicas: 3


